/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
package com.tec.parquimetro.parquimetro.GUI;
import com.tec.parquimetro.parquimetro.Clases.Administrador;
import com.tec.parquimetro.parquimetro.Clases.Espacio;
import com.tec.parquimetro.parquimetro.Clases.Inspector;
import com.tec.parquimetro.parquimetro.Clases.Parqueo;
import com.tec.parquimetro.parquimetro.Clases.Persona;
import com.tec.parquimetro.parquimetro.Clases.Vehiculo;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carol_flgngfy
 */
public class MenuInspector extends javax.swing.JFrame {

    /**
     * Creates new form MenuInspector
     */
    public  static Inspector inspector = new Inspector();
    public MenuInspector(Inspector pinspector) {
        initComponents();
        
        
        inspector = pinspector;
        labelBienvenido.setText(inspector.getNombre() + " " + inspector.getApellidos());
        lblId.setText(inspector.getIdentificacion());
         pbTabl.setSelectedIndex(2);
        
         pbTabl.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) {
                return 0; // Hacer la altura de las pestañas cero para ocultarlas
            }
         });
         pbTabl.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) {
                return 0; // Hacer la altura de las pestañas cero para ocultarlas
            }
        });
         pbTabl.setBorder(BorderFactory.createEmptyBorder());
    }

    //FUNCION PARA VERIFICAR SI LA PLACA ESTÁ EN EL PARQUEO, retorna true si la placa está en el parqueo, false si no lo está
    public static boolean verificarPlacaParqueo(int placa, int numParqueo, Parqueo parqueo){
        ArrayList<Espacio> listaEspacios = parqueo.getEspacios();
        //2. verificar en esta lista si el parqueo ingresado existe, si no retorna FALSE, si si, continua
        Espacio espacioVerificar = null;
        for (Espacio cadaEspacio : listaEspacios){
            if (cadaEspacio.getNumero() == numParqueo){
                espacioVerificar = cadaEspacio;
                break;
            }
        }
        if (espacioVerificar == null){ //no existe ese espacio
            JOptionPane.showMessageDialog(null, "NO existe un espacio con ese número de parqueo", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            return true;
        }
        else{ //si existe ese espacio, revisar si el espacio está ocupado y si la placa corresponde al parqueo
            if (espacioVerificar.getEstado()){ //si el estado es true, está disponible
                JOptionPane.showMessageDialog(null, "El espacio está disponible, no hay ningun auto registrado a este espacio", "MULTA", JOptionPane.INFORMATION_MESSAGE);
                return true;
            } 
            else{ //el espacio está ocupado
                for (Vehiculo vehiculo : espacioVerificar.getVehiculos()){
                    if (!vehiculo.getPlaca().equals(placa)){ //si la placa es diferente al del vehiculo estacionado, hace una multa
                        JOptionPane.showMessageDialog(null, "El vehiculo pago no corresponde con la placa ingresada", "MULTA", JOptionPane.INFORMATION_MESSAGE);
                        return true;
                    }
                }
                JOptionPane.showMessageDialog(null, "La placa del vehiculo en el espacio corresponde al pago", "TODO EN ORDEN", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        }
    }    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRedondo1 = new com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo();
        jLabel1 = new javax.swing.JLabel();
        btnPerfil = new com.tec.parquimetro.parquimetro.GUI.RondedBordes();
        btnRevisarParqueos = new com.tec.parquimetro.parquimetro.GUI.RondedBordes();
        rondedBordes5 = new com.tec.parquimetro.parquimetro.GUI.RondedBordes();
        btnReportes = new com.tec.parquimetro.parquimetro.GUI.RondedBordes();
        labelBienvenido = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        pbTabl = new javax.swing.JTabbedPane();
        pnParquear = new com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo();
        lbRevisarParqueos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumParqueo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        pnReportes = new com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo();
        lblPerfil3 = new javax.swing.JLabel();
        pnPrincipal = new com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo();
        lblPerfil5 = new javax.swing.JLabel();
        pnPerfil = new com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo();
        lblPerfil6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtPt2Mail = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDireccionFisica = new javax.swing.JTextArea();
        txtIdentificacion = new javax.swing.JTextField();
        lblIdentificacion = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblTelefono1 = new javax.swing.JLabel();
        lblTelefono2 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtPt1Mail = new javax.swing.JTextField();
        lblApellidos1 = new javax.swing.JLabel();
        lblApellidos2 = new javax.swing.JLabel();
        lblApellidos3 = new javax.swing.JLabel();
        btnActualizarPerfil = new com.tec.parquimetro.parquimetro.GUI.RondedBordes();
        btnRestablecerContra = new com.tec.parquimetro.parquimetro.GUI.RondedBordes();
        jLabel3 = new javax.swing.JLabel();
        txtTerminal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 24, 39));

        panelRedondo1.setBackground(new java.awt.Color(57, 54, 66));
        panelRedondo1.setRoundBottomLeft(30);
        panelRedondo1.setRoundBottomRight(30);
        panelRedondo1.setRoundTopLeft(30);
        panelRedondo1.setRoundTopRight(30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Parquimetro");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btnPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnPerfil.setForeground(new java.awt.Color(0, 0, 51));
        btnPerfil.setText("Mi Perfil");
        btnPerfil.setColor1(new java.awt.Color(255, 255, 255));
        btnPerfil.setColor2(new java.awt.Color(255, 255, 255));
        btnPerfil.setColor3(new java.awt.Color(204, 204, 204));
        btnPerfil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPerfilMouseExited(evt);
            }
        });
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnRevisarParqueos.setForeground(new java.awt.Color(0, 0, 51));
        btnRevisarParqueos.setText("Revisar parqueos");
        btnRevisarParqueos.setColor1(new java.awt.Color(255, 255, 255));
        btnRevisarParqueos.setColor2(new java.awt.Color(255, 255, 255));
        btnRevisarParqueos.setColor3(new java.awt.Color(204, 204, 204));
        btnRevisarParqueos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRevisarParqueos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevisarParqueosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevisarParqueosMouseExited(evt);
            }
        });
        btnRevisarParqueos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarParqueosActionPerformed(evt);
            }
        });

        rondedBordes5.setText("Cerrar Sesion");
        rondedBordes5.setToolTipText("");
        rondedBordes5.setColor1(new java.awt.Color(126, 217, 87));
        rondedBordes5.setColor2(new java.awt.Color(126, 217, 87));
        rondedBordes5.setColor3(new java.awt.Color(126, 217, 87));
        rondedBordes5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rondedBordes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rondedBordes5ActionPerformed(evt);
            }
        });

        btnReportes.setForeground(new java.awt.Color(0, 0, 51));
        btnReportes.setText("Reportes");
        btnReportes.setColor1(new java.awt.Color(255, 255, 255));
        btnReportes.setColor2(new java.awt.Color(255, 255, 255));
        btnReportes.setColor3(new java.awt.Color(204, 204, 204));
        btnReportes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportesMouseExited(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        labelBienvenido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenido.setText("Camila Araya Conejo");

        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("305610469");

        javax.swing.GroupLayout panelRedondo1Layout = new javax.swing.GroupLayout(panelRedondo1);
        panelRedondo1.setLayout(panelRedondo1Layout);
        panelRedondo1Layout.setHorizontalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo1Layout.createSequentialGroup()
                .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondo1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(labelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRedondo1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblId))
                    .addGroup(panelRedondo1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondo1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rondedBordes5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRevisarParqueos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        panelRedondo1Layout.setVerticalGroup(
            panelRedondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondo1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId)
                .addGap(33, 33, 33)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnRevisarParqueos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rondedBordes5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pbTabl.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        pbTabl.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        pbTabl.setToolTipText("");

        pnParquear.setBackground(new java.awt.Color(57, 54, 66));
        pnParquear.setRoundBottomLeft(15);
        pnParquear.setRoundBottomRight(15);
        pnParquear.setRoundTopLeft(15);
        pnParquear.setRoundTopRight(15);

        lbRevisarParqueos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbRevisarParqueos.setForeground(new java.awt.Color(255, 255, 255));
        lbRevisarParqueos.setText("Revisar parqueos");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese el número de placa:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Ingrese el número del parqueo:");

        txtNumParqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumParqueoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnParquearLayout = new javax.swing.GroupLayout(pnParquear);
        pnParquear.setLayout(pnParquearLayout);
        pnParquearLayout.setHorizontalGroup(
            pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParquearLayout.createSequentialGroup()
                .addGroup(pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnParquearLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPlaca)
                            .addComponent(txtNumParqueo, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                    .addGroup(pnParquearLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lbRevisarParqueos))
                    .addGroup(pnParquearLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        pnParquearLayout.setVerticalGroup(
            pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnParquearLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lbRevisarParqueos)
                .addGap(97, 97, 97)
                .addGroup(pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnParquearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumParqueo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(btnBuscar)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        pbTabl.addTab("", pnParquear);

        pnReportes.setBackground(new java.awt.Color(57, 54, 66));
        pnReportes.setRoundBottomLeft(15);
        pnReportes.setRoundBottomRight(15);
        pnReportes.setRoundTopLeft(15);
        pnReportes.setRoundTopRight(15);

        lblPerfil3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPerfil3.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfil3.setText("Reportes");

        javax.swing.GroupLayout pnReportesLayout = new javax.swing.GroupLayout(pnReportes);
        pnReportes.setLayout(pnReportesLayout);
        pnReportesLayout.setHorizontalGroup(
            pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnReportesLayout.createSequentialGroup()
                .addContainerGap(692, Short.MAX_VALUE)
                .addComponent(lblPerfil3)
                .addGap(40, 40, 40))
        );
        pnReportesLayout.setVerticalGroup(
            pnReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReportesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPerfil3)
                .addContainerGap(601, Short.MAX_VALUE))
        );

        pbTabl.addTab("", pnReportes);

        pnPrincipal.setBackground(new java.awt.Color(57, 54, 66));
        pnPrincipal.setRoundBottomLeft(15);
        pnPrincipal.setRoundBottomRight(15);
        pnPrincipal.setRoundTopLeft(15);
        pnPrincipal.setRoundTopRight(15);

        lblPerfil5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPerfil5.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfil5.setText("PARQUIMETRO");

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(lblPerfil5)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(lblPerfil5)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pbTabl.addTab("", pnPrincipal);

        pnPerfil.setBackground(new java.awt.Color(57, 54, 66));
        pnPerfil.setRoundBottomLeft(15);
        pnPerfil.setRoundBottomRight(15);
        pnPerfil.setRoundTopLeft(15);
        pnPerfil.setRoundTopRight(15);

        lblPerfil6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPerfil6.setForeground(new java.awt.Color(255, 255, 255));
        lblPerfil6.setText("Mi Perfil");

        txtTelefono.setText("00000000");
        txtTelefono.setToolTipText("Telefono");
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        txtPt2Mail.setToolTipText("Dominio");

        txtApellidos.setText("Apellidos");
        txtApellidos.setToolTipText("Apellidos");
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        taDireccionFisica.setColumns(20);
        taDireccionFisica.setRows(5);
        taDireccionFisica.setToolTipText("Direccion Fisica");
        jScrollPane1.setViewportView(taDireccionFisica);

        txtIdentificacion.setToolTipText("Identificacion");

        lblIdentificacion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblIdentificacion.setForeground(new java.awt.Color(255, 255, 255));
        lblIdentificacion.setText("Identificacion");

        lblApellidos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos");

        lblNombre1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("Nombre");

        lblTelefono1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono1.setText("Telefono");

        lblTelefono2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTelefono2.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono2.setText("Direccion Fisica");

        txtNombre1.setToolTipText("Nombre");
        txtNombre1.setCaretColor(new java.awt.Color(102, 255, 102));
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });

        txtPt1Mail.setToolTipText("Nombre");

        lblApellidos1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblApellidos1.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos1.setText("Dominio de correo electronico");

        lblApellidos2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblApellidos2.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos2.setText("@");

        lblApellidos3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblApellidos3.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos3.setText("Encabezado de correo electronico");

        btnActualizarPerfil.setBackground(new java.awt.Color(255, 145, 77));
        btnActualizarPerfil.setText("Actualizar");
        btnActualizarPerfil.setToolTipText("Actualizar");
        btnActualizarPerfil.setColor1(new java.awt.Color(204, 102, 0));
        btnActualizarPerfil.setColor2(new java.awt.Color(204, 102, 0));
        btnActualizarPerfil.setColor3(new java.awt.Color(204, 102, 0));
        btnActualizarPerfil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnActualizarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPerfilActionPerformed(evt);
            }
        });

        btnRestablecerContra.setBackground(new java.awt.Color(111, 158, 94));
        btnRestablecerContra.setText("Restablecer contrasena");
        btnRestablecerContra.setToolTipText("Restablecer contrasena");
        btnRestablecerContra.setColor1(new java.awt.Color(111, 158, 94));
        btnRestablecerContra.setColor2(new java.awt.Color(111, 158, 94));
        btnRestablecerContra.setColor3(new java.awt.Color(111, 158, 94));
        btnRestablecerContra.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRestablecerContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerContraActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Terminal");

        javax.swing.GroupLayout pnPerfilLayout = new javax.swing.GroupLayout(pnPerfil);
        pnPerfil.setLayout(pnPerfilLayout);
        pnPerfilLayout.setHorizontalGroup(
            pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPerfilLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPerfilLayout.createSequentialGroup()
                        .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdentificacion)
                            .addComponent(lblTelefono1)
                            .addGroup(pnPerfilLayout.createSequentialGroup()
                                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(txtPt1Mail))
                                .addGap(35, 35, 35)
                                .addComponent(lblApellidos2))
                            .addComponent(lblApellidos3)
                            .addComponent(lblNombre1)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellidos)
                            .addComponent(lblTelefono2)
                            .addComponent(lblApellidos1)
                            .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtApellidos)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(txtPt2Mail)))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPerfilLayout.createSequentialGroup()
                        .addComponent(btnRestablecerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))))
            .addGroup(pnPerfilLayout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(lblPerfil6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnPerfilLayout.setVerticalGroup(
            pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPerfilLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPerfil6)
                .addGap(28, 28, 28)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(lblNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono1)
                    .addComponent(lblTelefono2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnPerfilLayout.createSequentialGroup()
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblIdentificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(36, 36, 36)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos1)
                    .addComponent(lblApellidos3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPt1Mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPt2Mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos2))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTerminal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(pnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pbTabl.addTab("", pnPerfil);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panelRedondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(pbTabl)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pbTabl)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelRedondo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        pbTabl.setSelectedIndex(4);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        pbTabl.setSelectedIndex(3);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnRevisarParqueosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarParqueosMouseEntered
        btnRevisarParqueos.setColor1(Color.orange);
        btnRevisarParqueos.setColor2(Color.orange);
        btnRevisarParqueos.setColor3(Color.orange);
        btnRevisarParqueos.setForeground(Color.white);
    }//GEN-LAST:event_btnRevisarParqueosMouseEntered

    private void btnRevisarParqueosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarParqueosMouseExited
        btnRevisarParqueos.setColor1(Color.white);
        btnRevisarParqueos.setColor2(Color.white);
        btnRevisarParqueos.setColor3(Color.white);
        btnRevisarParqueos.setForeground(new Color(0,0,51));
    }//GEN-LAST:event_btnRevisarParqueosMouseExited

    private void btnRevisarParqueosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarParqueosActionPerformed

        pbTabl.setSelectedIndex(0);
    }//GEN-LAST:event_btnRevisarParqueosActionPerformed

    private void rondedBordes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rondedBordes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rondedBordes5ActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        pbTabl.setSelectedIndex(1);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        btnReportes.setColor1(Color.orange);
        btnReportes.setColor2(Color.orange);
        btnReportes.setColor3(Color.orange);
        btnReportes.setForeground(Color.white);
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseEntered
        btnPerfil.setColor1(Color.orange);
        btnPerfil.setColor2(Color.orange);
        btnPerfil.setColor3(Color.orange);
        btnPerfil.setForeground(Color.white);
    }//GEN-LAST:event_btnPerfilMouseEntered

    private void btnPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseExited
        btnPerfil.setColor1(Color.white);
        btnPerfil.setColor2(Color.white);
        btnPerfil.setColor3(Color.white);
        btnPerfil.setForeground(new Color(0,0,51));
    }//GEN-LAST:event_btnPerfilMouseExited

    private void btnReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseExited
        btnReportes.setColor1(Color.white);
        btnReportes.setColor2(Color.white);
        btnReportes.setColor3(Color.white);
        btnReportes.setForeground(new Color(0,0,51));
    }//GEN-LAST:event_btnReportesMouseExited

    private void btnRestablecerContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerContraActionPerformed
            String[] options = { "Si", "No" };
            var selection = JOptionPane.showOptionDialog(null, "Esta segur@ de restablecer la contrasena?", "Alerta!!", 
                                                              0, 3, null, options, options[0]);
            if (selection == 0) {


              }
            else{
                JOptionPane.showMessageDialog(null, "No se actualizara!");
            }
    }//GEN-LAST:event_btnRestablecerContraActionPerformed

        //VALIDACIONES DATOS DE PERFIL
    public boolean validarApellidos(String apellidos) {
        
        if(apellidos.length()>= 1 && apellidos.length()<=40){
            return true;
        }
        else
            return false;
        
    }

   public boolean validarNombre(String nombre) {
        
        if(nombre.length() >= 2 && nombre.length()<=20){
                 return true;
        }
        return false;
        
    }
   
  public boolean validarTelefono(int telefono) {
        
        //es caso de tener 8 digito su resultado
        if(telefono / 100000000 == 0){
            return true;
        }
        else
            return false;
        
        
    }
  
 public boolean setFechaIngreso(LocalDate fechaIngreso) {
        
        
        LocalDate hoy = LocalDate.now();
        if(fechaIngreso.isBefore(hoy) || fechaIngreso.isEqual(hoy)){
            return true;
        }
        else
            return false;
        
    }
 
 public boolean validacionIdentificacion(String identificacion) {
        
        if(identificacion.length()>= 2 && identificacion.length() <= 25){
            return true;
        }
        else{
            
            return false;
        
        }
    }
 
     public boolean  validacionDireccionFisica(String direccionFisica) {
        
        if(direccionFisica.length() >= 5 && direccionFisica.length() <= 50){
            
            return true;
            
        }else{
        
            return false;
        }
        
    }
     
    public boolean validarPin(String pin){
    
        if(pin.length() == 5){
            return true;
        }
        else{
            return false;
        }
    }   
    
   private boolean validarConversion(String elemento){
            
        try{
        
            int prueba = Integer.valueOf(elemento);
            return true;
        }
        catch(NumberFormatException e){
            return false;
        }
        
    }
   
       private boolean validarTerminalInspeccion(String terminal){
        
        if(terminal.length() == 6)
            return true;
        else
            return false;
    
    }
    
    
    private void btnActualizarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPerfilActionPerformed
        String nombre;
        String apellidos;
        String identidicacion;
        String direccionFisica;
        int telefono;
        
        
        if(validarNombre(txtNombre1.getText())){
        
                if(validarApellidos(txtApellidos.getText())){
                    
                   if(validacionDireccionFisica(taDireccionFisica.getText())){
                       
                       if(validacionIdentificacion(txtIdentificacion.getText())){
                           if(validarConversion(txtTelefono.getText())){
                           
                               if(validarTelefono(Integer.parseInt(txtTelefono.getText()))){
                               
                                    if(validarTerminalInspeccion(txtTerminal.getText())){
                                       
                                           Persona inspector = new Inspector();
                                       
                                       }
                                       else{
                                            JOptionPane.showMessageDialog(null, "La terminal debe tener 6 caracteres!");
                                       }
                                   
                               }
                               else{
                                    JOptionPane.showMessageDialog(null, "El telefono debe tener 8 digitos!");
                               }
                           }
                           else{
                                JOptionPane.showMessageDialog(null, "El telefono posee caracteres alfabeticos!");
                           }
                       }
                       else{
                            JOptionPane.showMessageDialog(null, "La identificacion debe tener entre 2 a 25 caracteres!");
                       }
                   }
                   else{
                    JOptionPane.showMessageDialog(null, "La direccion fisica debe tener entre 5 a 60 caracteres!");
                   }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Los apellidos deben tener entre 1 a 40 caracteres!");
                }
                
        }
        else{
             JOptionPane.showMessageDialog(null, "El nombre debe tener entre 2 a 20 caracteres!");
        }
    }//GEN-LAST:event_btnActualizarPerfilActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNumParqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumParqueoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumParqueoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInspector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInspector(inspector).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.tec.parquimetro.parquimetro.GUI.RondedBordes btnActualizarPerfil;
    private javax.swing.JButton btnBuscar;
    private com.tec.parquimetro.parquimetro.GUI.RondedBordes btnPerfil;
    private com.tec.parquimetro.parquimetro.GUI.RondedBordes btnReportes;
    private com.tec.parquimetro.parquimetro.GUI.RondedBordes btnRestablecerContra;
    private com.tec.parquimetro.parquimetro.GUI.RondedBordes btnRevisarParqueos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JLabel lbRevisarParqueos;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblApellidos1;
    private javax.swing.JLabel lblApellidos2;
    private javax.swing.JLabel lblApellidos3;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPerfil3;
    private javax.swing.JLabel lblPerfil5;
    private javax.swing.JLabel lblPerfil6;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JLabel lblTelefono2;
    private com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo panelRedondo1;
    private javax.swing.JTabbedPane pbTabl;
    private com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo pnParquear;
    private com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo pnPerfil;
    private com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo pnPrincipal;
    private com.tec.parquimetro.parquimetro.GUI.Componentes.PanelRedondo pnReportes;
    private com.tec.parquimetro.parquimetro.GUI.RondedBordes rondedBordes5;
    private javax.swing.JTextArea taDireccionFisica;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNumParqueo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPt1Mail;
    private javax.swing.JTextField txtPt2Mail;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTerminal;
    // End of variables declaration//GEN-END:variables
}*/
